<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <BaseOutputPath>..\lib\</BaseOutputPath>
    <NoWarn>1591</NoWarn>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="antokhio.YogaSharp" Version="1.1.3" />
    <PackageReference Include="SkiaSharp" Version="2.88.8" />
    <PackageReference Include="VL.Core" Version="$(VLVersion)" />
    <PackageReference Include="VL.Core.Skia" Version="$(VLVersion)" />
    <PackageReference Include="VL.CoreLib" Version="$(VLVersion)" />
  </ItemGroup>
</Project>
