<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseWindowsForms>true</UseWindowsForms>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <BaseOutputPath>..\lib\</BaseOutputPath>
    <NoWarn>1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="VL.Core" Version="$(VLVersion)" />
    <PackageReference Include="VL.Core.Skia" Version="$(VLVersion)" />
    <PackageReference Include="VL.CoreLib" Version="$(VLVersion)" />
  </ItemGroup>
</Project>
