<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>..\lib</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Stride.Input" Version="4.2.0.2121" />
    <PackageReference Include="VL.Core" Version="2024.6.7" />
    <PackageReference Include="VL.Core.Skia" Version="2024.6.7" />
  </ItemGroup>

</Project>
